name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            name: windows-x86_64.zip
          - target: i686-pc-windows-gnu
            name: windows-i686.zip
          - target: x86_64-unknown-linux-gnu
            name: linux-x86_64.tar.gz
          - target: i686-unknown-linux-gnu
            name: linux-i686.tar.gz
          - target: aarch64-unknown-linux-gnu
            name: linux-aarch64.tar.gz
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Install GCC for Windows x86_64
        if: ${{ matrix.target == 'x86_64-pc-windows-gnu' }}
        run: sudo apt update && sudo apt install gcc-mingw-w64-x86-64
      - name: Install GCC for Windows i686
        if: ${{ matrix.target == 'i686-pc-windows-gnu' }}
        run: sudo apt update && sudo apt install gcc-mingw-w64-i686
      - name: Install GCC for Linux i686
        if: ${{ matrix.target == 'i686-unknown-linux-gnu' }}
        run: sudo apt update && sudo apt install gcc-multilib
      - name: Install GCC for Linux aarch64
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu
      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}
      - name: Get binaries path
        run: export BINARIES=$(cargo build -q --message-format=json-render-diagnostics --release --locked --target ${{ matrix.target }} | jq -r 'select(.reason == "compiler-artifact") | select(.executable != null) | .executable')
      - name: Create archive for Linux
        if: ${{ contains(matrix.target, 'linux') }}
        run: bins=($BINARIES); tar -czf ${{ matrix.name }} -C $(dirname ${bins[0]}) $(for bin in ${bins[@]}; do basename $bin; done)
      - name: Create archive for Windows
        if: ${{ contains(matrix.target, 'windows')}}
        run: bins=($BINARIES); zip -j ${{ matrix.name }} $(for bin in ${bins[@]}; do echo -n "$bin "; done)
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.name }}
          tag: ${{ github.ref }}
